---
# To overwrite a specific section of common_properties, add the desired property with a new value after the '<<: *common_properties' line in the corresponding section

common_properties: &common_properties
  security_alerts: true
  exclude_labels:
    - WIP
    - ignore
  use_labels: true
  exclude_titles:
    - DO NOT MERGE
    - PROTOTYPE
    - WIP
    - DNM
    - DRAFT
    - PARKED
  quotes_days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

# di-architecture:
#   channel: '#di-architecture'
#   <<: *common_properties
#   repos:
#     - digital-identity-architecture

# di-ipv-orange-cri-maintainers:
#   channel: '#di-cri-orange-team-tech'
#   <<: *common_properties
#   repos:
#     - di-ipv-acceptance-tests
#     - di-ipv-config
#     - di-ipv-cri-address-api
#     - di-ipv-cri-address-front
#     - di-ipv-cri-check-hmrc-api
#     - di-ipv-cri-check-hmrc-front
#     - di-ipv-cri-common-express
#     - di-ipv-cri-common-infrastructure
#     - di-ipv-cri-common-lambdas
#     - di-ipv-cri-dev-tools
#     - di-ipv-cri-kbv-api
#     - di-ipv-cri-kbv-front
#     - di-ipv-cri-kbv-hmrc-api
#     - di-ipv-cri-kbv-hmrc-front
#     - di-ipv-cri-lib
#     - di-ipv-cri-otg-hmrc
#     - di-ipv-cri-pipeline-deployment
#     - di-ipv-cri-tech-docs
#     - di-ipv-cri-templates
#     - di-ipv-cri-toy-api
#     - di-ipv-cri-toy-front
#   security_alerts: false

# di-one-login-home:
#   channel: "#di-one-login-home"
#   quotes:
#     - We put users first. We strive to create services that bring real value to our users and that meet their needs and expectations.
#     - We believe users should feel safe and confident when they use our services.
#     - We design for everyone. We think about under-represented audiences from the start and check our biases throughout the design process.
#     - We’re comfortable challenging assumptions and asking difficult questions. We speak truth to power.
#     - We’re OK with change, failure, ambiguity, and adapting our approach.
#     - We work collaboratively. Our work does not happen in discipline silos and we value the contributions of every discipline equally.
#     - We treat each other with integrity, honesty and respect.
#     - We work in the open so users and government colleagues know what we’re doing and why.
#     - We know we can't do this alone. We need to work with teams across GDS and government to succeed.
#     - We invest time and effort in increasing our understanding of the problems we’re working on. This will help us make things better for users and move the conversation about personalisation in government forward.

# di-one-login-home-tech:
#   channel: "#di-one-login-home-tech"
#   <<: *common_properties
#   repos:
#     - di-account-management-backend
#     - di-account-management-frontend
#     - di-accounts-infra
#     - di-govuk-one-login-service-header
#   security_alerts: false

# dev-platform-team:
#   channel: '#di-dev-platform-team-internal'
#   <<: *common_properties
#   quotes:
#     - We put users first. We strive to create services that bring real value to our users and that meet their needs and expectations.
#     - We believe users should feel safe and confident when they use our services.
#     - We’re comfortable challenging assumptions and asking difficult questions. We speak truth to power.
#     - We’re OK with change, failure, ambiguity, and adapting our approach.
#     - We work collaboratively. Our work does not happen in discipline silos and we value the contributions of every discipline equally.
#     - We treat each other with integrity, honesty and respect.
#     - We work in the open so users and government colleagues know what we’re doing and why.
#     - We know we can't do this alone. We need to work with teams across GDS and government to succeed.
#     - We invest time and effort in increasing our understanding of the problems we’re working on. This will help us make things better for users and move the conversation about personalisation in government forward.
#     - 'Remember to make time for personal-development :big-brain:'
#     - 'Remember to celebrate our successes :tada:'
#     - We believe in the power of documentation.
#     - We believe that no bug should occur twice, but if it does, we will be able to fix it following documentation.
#   repos:
#     - di-devplatform-deploy
#     - di-devplatform-demo-sam-app
#     - di-devplatform-utils
#     - di-devplatform-infra-audit-hook
#     - di-devplatform-lambda-audit-hook
#     - di-devplatform-upload-action
#     - di-devplatform-upload-action-ecr
#     - di-devplatform-metriccollector
#     - di-devplatform-checkov-hook
#     - di-devplatform-container-verifier
#     - di-devplatform-auth-api-test
