payments_infrastructure:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo

  github_team: "payments-infrastructure-be"

  channel: "#squad-payments_infrastructure-devs"

security_alerts:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"
    - "maintenance-upgrade"

  use_labels: true

  include_repos:
    - meetcleo

  members:
    - "dependabot[bot]"

  channel: "#collab-first_responders"

github_bots:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo

  members:
    - "dependabot[bot]"
    - "sweepai[bot]"

  channel: "#collab-github-bots"

data:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - analytics

  members: []

  channel: "#collab-dbt-code-review"

payments_security_experience:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo

  github_team: "payments-experience"

  channel: "#squad-pse-dev"

seal_team:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - seal_the_revenge

  github_team: "seal_team"

  channel: "#proj-seal_bot"

data_science_engineers:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo

  github_team: "ds-eng"

  channel: "#squad-ds-eng-reviews"

pricing_and_lending:
  exclude_titles:
    - "WIP"

  exclude_labels:
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo

  github_team: "ds-payments-and-lending-be"

  channel: "#squad-pricing_and_lending-devs"

