payments_infrastructure:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "payments-infrastructure-be"

  channel: "#squad-payments_infrastructure-devs"

security_alerts:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"
    - "maintenance-upgrade"

  use_labels: true

  include_repos:
    - meetcleo

  members:
    - "dependabot[bot]"

  channel: "#alerts-first_responders"

github_bots:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  members:
    - "dependabot[bot]"
    - "sweepai[bot]"

  channel: "#collab-github-bots"

data:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - analytics

  members: []

  channel: "#collab-dbt-code-review"

plus:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "plus"

  channel: "#squad-cleo_plus-dev"

seal_team:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - seal_the_revenge

  github_team: "seal_team"

  channel: "#proj-seal_bot"

cash_advance:
  # Working on the assumption that PRs we don't want to merge should be
  # converted to Draft PRs instead of relying on labels and titles.
  exclude_titles: []
  exclude_labels: []

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "cash-advance"
  channel: "#squad-cash_advance-devs"

card_2:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "card-2"

  channel: "#squad-honet_badgers-devs"
