seal_team:
  channel: "#seal-bot-test"
  members:
    - naeglinghaff
  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"
  use_labels: true
  exclude_labels:
    - "wip"
    - "WIP"
    - "ignore"
  github_team: "seal_team"
