payments_infrastructure:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "payments-infrastructure-be"

  channel: "#squad-payments_infrastructure-devs"

security_alerts_web_and_be:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"
    - "maintenance-upgrade"

  use_labels: true

  include_repos:
    - meetcleo

  members:
    - "dependabot[bot]"

  channel: "#alerts-first_responders"

security_alerts_app:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"
    - "maintenance-upgrade"

  use_labels: true

  include_repos:
    - mobile-app

  members:
    - "dependabot[bot]"

  channel: "#collab-frontend-first-responders"

github_bots:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  members:
    - "dependabot[bot]"
    - "sweepai[bot]"

  channel: "#collab-github-bots"

data:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - analytics

  members: []

  channel: "#collab-dbt-code-review"

ewa_progression:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "ewa-progression"

  channel: "#squad-ewa_progression-dev"

seal_team:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - seal_the_revenge

  github_team: "seal_team"

  channel: "#proj-seal_bot"

ewa_core:
  exclude_titles: []
  exclude_labels: []

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "ewa-core"
  channel: "#squad-ewa_core-devs"

ewa_modelling:
  exclude_titles: []
  exclude_labels:
    - "Do Not Merge"
    - "destroy"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app
    - data-science-services
    - cleo-flux
    - general-infra

  github_team: "ewa-modelling"
  channel: "#squad-ewa_modelling-devs"

card_2:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "card-2"

  channel: "#squad-honet_badgers-devs"

ufu:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo

  github_team: "ufu-be"
  channel: "#squad-ufu-eng"

marketplace:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "marketplace"
  channel: "#squad-marketplace"
