payments_infrastructure:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "payments-infrastructure-be"

  channel: "#squad-payments_infrastructure-devs"

security_alerts:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"
    - "maintenance-upgrade"

  use_labels: true

  include_repos:
    - meetcleo

  members:
    - "dependabot[bot]"

  channel: "#alerts-first_responders"

github_bots:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  members:
    - "dependabot[bot]"
    - "sweepai[bot]"

  channel: "#collab-github-bots"

data:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - analytics

  members: []

  channel: "#collab-dbt-code-review"

cash_advance_1:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "cash-advance-1"

  channel: "#squad-cash_advance_1-dev"

seal_team:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - seal_the_revenge

  github_team: "seal_team"

  channel: "#proj-seal_bot"

pricing_and_lending:
  exclude_titles:
    - "WIP"
    - "[WIP]"

  exclude_labels:
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo

  github_team: "pricing-and-lending-be"

  channel: "#squad-pricing_and_lending-devs"

card_2:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Do Not Merge"

  use_labels: true

  include_repos:
    - meetcleo
    - mobile-app

  github_team: "card-2"

  channel: "#squad-honet_badgers-devs"
