monet:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  repos:
    - meetcleo

  members:
    - AgentAntelope
    - RSijelmass
    - wilco3d

  channel: "#monet_squad"

payments_infrastructure:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  repos:
    - meetcleo

  members:
    - ClemCB
    - davefrey
    - kofibright
    - sachimp
    - tomwhatmore
    - toypadlock
    - FriedSock
    - joelbiffin

  channel: "#payments-infrastructure-internal"

odyssey:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  repos:
    - meetcleo

  members:
    - SaraBon
    - iconpin
    - tarawud
    - naeglinghaff
    - stevehook

  channel: "#cash-advance-odyssey-dev"

security_alerts:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  repos:
    - meetcleo

  members:
    - "dependabot[bot]"

  channel: "#first-responders"

data:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  repos:
    - analytics

  members: []

  channel: "#dbt-code-review"

payments_security_experience:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  repos:
    - meetcleo

  members:
    - CliffAw
    - DhirenAtodaria
    - repoocuts
    - karimtimer

  channel: "##payments-security-experience-dev"

seal_team:
  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  exclude_labels:
    - "Waiting on copy"
    - "Do Not Merge"

  use_labels: true

  repos:
    - seal_the_revenge

  github_team: "seal_team"

  channel: "#seal-bot-test"
