name: Lint GitHub Actions
on:
  push:
    paths: ['.github/**']
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          show-progress: false
      - uses: alphagov/govuk-infrastructure/.github/actions/actionlint@main
