name: "Dependapanda"

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '00 9 * * 1-5' # Runs at 9:00 UTC, Monday through Friday.

env:
  SEAL_ORGANISATION: alphagov
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  dependapanda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup ruby
        uses: ruby/setup-ruby@efbf473cab83af4468e8606cc33eca9281bb213f # v1.256.0
        with:
          bundler-cache: true

      - name: Dependapanda
        id: dependapanda
        run: ./bin/seal_runner.rb dependapanda

      - if: ${{ failure() }}
        uses: alphagov/govuk-infrastructure/.github/actions/report-run-failure@main
        with:
          slack_webhook_url: ${{ secrets.GOVUK_SLACK_WEBHOOK_URL }}
          channel: govuk-platform-support
          message: "Dependapanda workflow failed"
