name: "Gem Version Checker"

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '00 13 * * 3' # Runs at 13:00 UTC, Every Wednesday.

env:
  SEAL_ORGANISATION: alphagov
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  gem-version-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          bundler-cache: true

      - name: Gem Version Checker
        id: gem_version_checker
        run: |
          ./bin/seal_runner.rb gems

      - if: ${{ failure() }}
        uses: alphagov/govuk-infrastructure/.github/actions/report-run-failure@main
        with:
          slack_webhook_url: ${{ secrets.GOVUK_SLACK_WEBHOOK_URL }}
          channel: govuk-platform-support
          message: "Gem Version Checker workflow failed"
