name: "Gem Version Checker"

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '00 13 * * 3' # Runs at 13:00 UTC, Every Wednesday.

env:
  SEAL_ORGANISATION: alphagov
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  gem-version-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true

      - name: Gem Version Checker
        id: gem_version_checker
        run: |
          ./bin/seal_runner.rb gems

      - if: ${{ failure() }}
        uses: alphagov/govuk-infrastructure/.github/actions/report-run-failure@main
        with:
          slack_webhook_url: ${{ secrets.GOVUK_SLACK_WEBHOOK_URL }}
          channel: govuk-platform-support
          message: "Gem Version Checker workflow failed"
