name: "Gem Version Checker"

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '00 13 * * 3' # Runs at 13:00 UTC, Every Wednesday.

env:
  SEAL_ORGANISATION: alphagov
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  gem-version-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup ruby
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          bundler-cache: true

      - name: Gem Version Checker
        id: gem_version_checker
        run: |
          ./bin/seal_runner.rb gems

      - if: ${{ failure() }}
        uses: alphagov/govuk-infrastructure/.github/actions/report-run-failure@main
        with:
          slack_webhook_url: ${{ secrets.GOVUK_SLACK_WEBHOOK_URL }}
          channel: govuk-platform-support
          message: "Gem Version Checker workflow failed"
